version: "3.8"

services:
  base-de-datos:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "DATABASE_NAME"
    volumes:
      - postgres-login-volumen:/var/lib/pgsql/data/
volumes:
  postgres-login-volumen: 